(setq-default filesets-be-docile-flag 'nil)

(setq filesets-submenus '("zelda-scripts" ("0 zelda-scripts" ["Files: zelda-scripts" (filesets-open ':files '"zelda-scripts")] "---" ["0 directions.gd" (filesets-file-open nil '"/home/dave/Documents/Studying/Prog/Godot/projects/Zelda/engine/directions.gd" '"zelda-scripts")] ["1 entity.gd" (filesets-file-open nil '"/home/dave/Documents/Studying/Prog/Godot/projects/Zelda/engine/entity.gd" '"zelda-scripts")] ["2 player.gd" (filesets-file-open nil '"/home/dave/Documents/Studying/Prog/Godot/projects/Zelda/player/player.gd" '"zelda-scripts")] ["3 stalfos.gd" (filesets-file-open nil '"/home/dave/Documents/Studying/Prog/Godot/projects/Zelda/enemies/stalfos.gd" '"zelda-scripts")] ["4 sword.gd" (filesets-file-open nil '"/home/dave/Documents/Studying/Prog/Godot/projects/Zelda/items/sword.gd" '"zelda-scripts")] ["5 sword.gd" (filesets-file-open nil '"/home/dave/Documents/Studying/Prog/Godot/projects/Zelda/items/sword.gd" '"zelda-scripts")] "---" ["Close all files" (filesets-close ':files '"zelda-scripts")] ["Run Command" (filesets-run-cmd nil '"zelda-scripts" ':files)] ["Add current buffer" (filesets-add-buffer '"zelda-scripts" (current-buffer))] ["Remove current buffer" (filesets-remove-buffer '"zelda-scripts" (current-buffer))] ["Rebuild this submenu" (filesets-rebuild-this-submenu '"zelda-scripts")])))

(setq filesets-menu-cache '(("0 zelda-scripts" ["Files: zelda-scripts" (filesets-open ':files '"zelda-scripts")] "---" ["0 directions.gd" (filesets-file-open nil '"/home/dave/Documents/Studying/Prog/Godot/projects/Zelda/engine/directions.gd" '"zelda-scripts")] ["1 entity.gd" (filesets-file-open nil '"/home/dave/Documents/Studying/Prog/Godot/projects/Zelda/engine/entity.gd" '"zelda-scripts")] ["2 player.gd" (filesets-file-open nil '"/home/dave/Documents/Studying/Prog/Godot/projects/Zelda/player/player.gd" '"zelda-scripts")] ["3 stalfos.gd" (filesets-file-open nil '"/home/dave/Documents/Studying/Prog/Godot/projects/Zelda/enemies/stalfos.gd" '"zelda-scripts")] ["4 sword.gd" (filesets-file-open nil '"/home/dave/Documents/Studying/Prog/Godot/projects/Zelda/items/sword.gd" '"zelda-scripts")] ["5 sword.gd" (filesets-file-open nil '"/home/dave/Documents/Studying/Prog/Godot/projects/Zelda/items/sword.gd" '"zelda-scripts")] "---" ["Close all files" (filesets-close ':files '"zelda-scripts")] ["Run Command" (filesets-run-cmd nil '"zelda-scripts" ':files)] ["Add current buffer" (filesets-add-buffer '"zelda-scripts" (current-buffer))] ["Remove current buffer" (filesets-remove-buffer '"zelda-scripts" (current-buffer))] ["Rebuild this submenu" (filesets-rebuild-this-submenu '"zelda-scripts")])))

(setq filesets-ingroup-cache 'nil)

(setq filesets-cache-version "1.8.4")

