(setq sml/replacer-regexp-list
	`((,(concat "^" (if (boundp 'org-directory)
			    (regexp-quote org-directory) "~/org/")) ":Org:")
	  ("^~/\\.emacs\\.d/elpa/" ":ELPA:")
	  ("^/home/Documents/Org" ":org:")
	  ("^/home/Documents/Study/Adventure" ":adv:")
	  ("^/home/mrbig/Documents/Study" ":study:")
	  ("^/home/Documents/Ebooks/IT" ":it:")
	  ("^/home/Documents/Ebooks/" ":bks:")
	  ("^~/Documents/" ":docs:")
	  ("^/home/maps" ":maps:")
	  ("^~/\\.emacs\\.d/" ":emacs:")
	  ("^~\\.config/" ":config:")
	  ("^/home/dotfiles/emacs/emacs_default/" ":emacs:")
	  ("^/home/dotfiles/scripts" ":scripts:")
	  ("^/home/dotfiles/" ":dotfiles:")
	  ("^~/Dropbox/" ":DB:")
	  ("^/sudo:.*:" ":SU:")
	  ("^:\\([^:]*\\):Documento?s/" ":\\1/Doc:")
	  ("^~/[Gg]it/" ":Git:")
	  ("^~/[Gg]it[Hh]ub/" ":Git:")
	  ("^~/[Gg]it\\([Hh]ub\\|\\)-?[Pp]rojects/" ":Git:")))
