(setq company-show-numbers t)

(setq company-idle-delay 0.5)
(setq-default company-idle-delay 0.5)

(setq company-auto-complete t)
(setq company-tooltip-limit 10)
(setq company-dabbrev-code-modes t)
(setq company-dabbrev-downcase nil)
(setq company-dabbrev-ignore-case t)
(setq company-dabbrev-other-buffers t)
(setq company-selection-wrap-around t)
(setq company-minimum-prefix-length 2)
(setq company-dabbrev-code-everywhere t)
(setq company-auto-complete-chars '(46))
(setq company-dabbrev-code-ignore-case t)
(setq company-dabbrev-ignore-buffers "nil")
