(setq ranger-minimal t)
;; Was preventing me from toggle their visibility
;; (setq ranger-show-hidden t)

(setq ranger-footer-delay 0)
(setq ranger-parent-depth 1)
(setq ranger-preview-file nil)
(setq ranger-override-dired t)
(setq ranger-persistent-sort t)
(setq ranger-cleanup-eagerly t)
(setq ranger-dont-show-binary t)
(setq ranger-width-preview 0.40)
(setq ranger-width-parents 0.20)
(setq ranger-max-preview-size 0.1)
(setq ranger-cleanup-on-disable t)
(setq ranger-return-to-ranger nil)
(setq ranger-deer-show-details nil)
(setq ranger-max-parent-width 0.45)
(setq ranger-excluded-extensions '("mkv" "iso" "mp4" "bin" "exe" "msi" "pdf" "doc" "docx"))
